requires 'Catalyst::Runtime',                              '5.90130';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Redis::Fast';
requires 'Catalyst::Plugin::Authentication',               '0.10023';
requires 'Catalyst::Plugin::Authorization::ACL',           '0.16';
requires 'Catalyst::Plugin::Authorization::Roles',         '0.09';
requires 'Catalyst::Plugin::OpenIDConnect',                '0.02';
requires 'Catalyst::Authentication::Store::DBIx::Class',   '0.1506';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::View::JSON';
requires 'Catalyst::View::TT';
requires 'Digest::SHA',                                    '6.04';
requires 'Crypt::SaltedHash',                              '0.09';
requires 'Config::YAML';
requires 'JSON::MaybeXS';
requires 'Cpanel::JSON::XS';
requires 'DBIx::Class';
requires 'Moose';
requires 'Moose::Util::TypeConstraints';
requires 'Readonly';
requires 'Text::CSV_XS';
requires 'Template';
requires 'DateTime';
requires 'DateTime::TimeZone';
requires 'Number::Format';
requires 'LWP';
requires 'LWP::Protocol::https';
requires 'HTTP::Cookies';
requires 'Term::ReadLine';
requires 'Term::ReadKey';
requires 'String::Range::Expand';
requires 'DBD::MariaDB';
requires 'YAML::XS';
requires 'JSON::XS';
requires 'OpenOffice::OODoc';
requires 'Exception::Class';
requires 'Try::Tiny::ByClass';
requires 'parent';
