FROM tfrayner/catalyst-base:1.1

# Install BeerFestDB dependencies.
WORKDIR /usr/src
COPY . .
RUN   cpanm --installdeps --with-recommends . \
   && rm -rf ~/.cpanm \
   && cd /usr && rm -rf /usr/src
WORKDIR /tmp
