# Generated by Django 5.2.8 on 2025-11-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BayPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litre_multiplier', models.DecimalField(decimal_places=12, max_digits=15)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_number', models.CharField(max_length=3)),
                ('currency_format', models.CharField(max_length=20)),
                ('exponent', models.SmallIntegerField()),
                ('currency_symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DispenseMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('is_disposable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fst_start_date', models.DateField(blank=True, null=True)),
                ('fst_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('awrs_urn', models.CharField(blank=True, max_length=31, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.companyregion')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(max_length=100, unique=True)),
                ('container_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.containermeasure')),
                ('dispense_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.dispensemethod')),
            ],
            options={
                'unique_together': {('container_volume', 'container_measure', 'dispense_method')},
            },
        ),
        migrations.CreateModel(
            name='CaskManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('stillage_bay', models.PositiveIntegerField(blank=True, null=True)),
                ('stillage_x_location', models.PositiveIntegerField(blank=True, null=True)),
                ('stillage_y_location', models.PositiveIntegerField(blank=True, null=True)),
                ('stillage_z_location', models.PositiveIntegerField(blank=True, null=True)),
                ('internal_reference', models.IntegerField(blank=True, null=True)),
                ('cellar_reference', models.IntegerField()),
                ('is_sale_or_return', models.BooleanField(default=False)),
                ('bar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.bar')),
                ('bay_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.bayposition')),
                ('distributor_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_casks', to='stock.company')),
                ('container_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.containersize')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.currency')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.festival')),
            ],
        ),
        migrations.AddField(
            model_name='bar',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.festival'),
        ),
        migrations.CreateModel(
            name='FestivalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.festival')),
                ('sale_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Gyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_reference', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('festival_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.festivalproduct')),
            ],
            options={
                'unique_together': {('festival_product', 'internal_reference')},
            },
        ),
        migrations.CreateModel(
            name='Cask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_vented', models.BooleanField(blank=True, null=True)),
                ('is_tapped', models.BooleanField(blank=True, null=True)),
                ('is_ready', models.BooleanField(blank=True, null=True)),
                ('is_condemned', models.BooleanField(default=False)),
                ('cask_management', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='stock.caskmanagement')),
                ('gyle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.gyle')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_time', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.festival')),
            ],
            options={
                'unique_together': {('festival', 'measurement_time')},
            },
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.festival')),
            ],
            options={
                'unique_together': {('festival', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nominal_abv', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cask_count', models.PositiveIntegerField()),
                ('advertised_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_final', models.BooleanField(blank=True, null=True)),
                ('is_received', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_sale_or_return', models.BooleanField(default=False)),
                ('container_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.containersize')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.currency')),
                ('distributor_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.company')),
                ('order_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.orderbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
            options={
                'unique_together': {('order_batch', 'product', 'distributor_company', 'container_size', 'cask_count', 'is_sale_or_return')},
            },
        ),
        migrations.AddField(
            model_name='caskmanagement',
            name='product_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.productorder'),
        ),
        migrations.CreateModel(
            name='ProductStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.productcategory')),
            ],
            options={
                'unique_together': {('product_category', 'description')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.productstyle'),
        ),
        migrations.CreateModel(
            name='SaleVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, unique=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('container_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.containermeasure')),
            ],
        ),
        migrations.AddField(
            model_name='festivalproduct',
            name='sale_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.salevolume'),
        ),
        migrations.CreateModel(
            name='StillageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.festival')),
            ],
            options={
                'unique_together': {('festival', 'description')},
            },
        ),
        migrations.AddField(
            model_name='caskmanagement',
            name='stillage_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stillagelocation'),
        ),
        migrations.CreateModel(
            name='CaskMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cask', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.cask')),
                ('container_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.containermeasure')),
                ('measurement_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.measurementbatch')),
            ],
            options={
                'unique_together': {('cask', 'measurement_batch')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='festivalproduct',
            unique_together={('festival', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='caskmanagement',
            unique_together={('festival', 'cellar_reference')},
        ),
    ]
