---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beerfestdb-code-pv-volume
  labels:
    type: local
    name: beerfestdb-codevol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/tfrayner/src/beerfestdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beerfestdb-code-pv-claim
  namespace: beerfestdb
spec:
  selector:
    matchLabels:
      name: beerfestdb-codevol
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beerfestdb
  name: beerfestdb-app
  labels:
    app: beerfestdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerfestdb-app
  template:
    metadata:
      labels:
        app: beerfestdb-app
    spec:
      containers:
      - name: beerfestdb
        image: tfrayner/beerfestdb:latest
        imagePullPolicy: IfNotPresent
        command: ["beerfestdb_web_fastcgi.pl", "-l", ":3000", "-n", "1"]
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: '1'
            memory: 4G
          requests:
            cpu: 10m
            memory: 200Mi
        securityContext:
          runAsUser: 65534  # nobody user
        envFrom:
        - configMapRef:
            name: beerfestdb-app-config
# Uncomment this for local development with a bind mount of the source code. Make 
# sure to set the BEERFESTDB_ROOT_PATH environment variable in the container. See .app_env for an example.
#        volumeMounts:
#        - mountPath: /usr/src/BeerFestDB
#          name: beerfestdb-codevol
#        workingDir: /usr/src/BeerFestDB
#      volumes:
#      - name: beerfestdb-codevol
#        persistentVolumeClaim:
#          claimName: beerfestdb-code-pv-claim
---
# For production we use an empty ConfigMap as a placeholder for configuration data. 
# Replace this with a ConfigMap built using e.g. the .app_env file contents for 
# local development, or switch to using a Secret if you want to store sensitive
# data like database credentials.
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beerfestdb
  name: beerfestdb-app-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: beerfestdb
  name: beerfestdb-app-service
spec:
  selector:
    app: beerfestdb-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx
  labels:
    app: beerfestdb-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerfestdb-nginx
  template:
    metadata:
      labels:
        app: beerfestdb-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.7-perl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: '1'
            memory: 4G
          requests:
            cpu: 10m
            memory: 200Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: beerfestdb-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx-service
spec:
  selector:
    app: beerfestdb-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
# # If you want to use cert-manager to get TLS certs from Let's Encrypt, you can
# # apply the following resources. You will need to replace the email address and
# # domain name with your own. Please note that this will only work on a publicly 
# # accessible cluster with a valid domain name pointing to it. If you are running
# # this on a local cluster or without a valid domain, you will need to use
# # self-signed certificates or another method for TLS.
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   namespace: beerfestdb
#   name: letsencrypt-prod
# spec:
#   acme:
#     email: user@example.org
#     server: https://acme-v02.api.letsencrypt.org/directory
#     privateKeySecretRef:
#       name: letsencrypt-prod-issuer-account-key
#     solvers:
#       - http01:
#           ingress:
#             serviceType: ClusterIP
#             ingressClassName: traefik
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   namespace: beerfestdb
#   name: beerfestdb-nginx-cert
# spec:
#   commonName: mybeerfestdb.example.net
#   secretName: beerfestdb-nginx-cert
#   dnsNames:
#     # Replace with your domain here
#     - mybeerfestdb.example.net
#   issuerRef:
#     kind: Issuer
#     name: letsencrypt-prod
# ---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: beerfestdb
  name: beerfestdb-ingress
spec:
# This entryPoint needs to be set up in your Traefik configuration to listen on the desired port (e.g. 8443 for HTTPS).
  entryPoints:
    - bfdbsecure
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: beerfestdb-nginx-service
      port: 80
# # If you have TLS set up, uncomment the following lines to enable TLS for the
# # ingress (see above for cert-manager resources)
#  tls:
#    secretName: beerfestdb-nginx-cert
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            fastcgi_pass beerfestdb-app-service:3000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param CONTENT_TYPE $content_type;
            fastcgi_param CONTENT_LENGTH $content_length;

            fastcgi_param SCRIPT_NAME  '';  
            fastcgi_param PATH_INFO $fastcgi_script_name; 
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_param DOCUMENT_URI $document_uri;
            fastcgi_param DOCUMENT_ROOT $document_root;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
  
            fastcgi_param GATEWAY_INTERFACE  CGI/1.1;
            fastcgi_param SERVER_SOFTWARE  nginx/$nginx_version;
  
            fastcgi_param REMOTE_ADDR $remote_addr;
            fastcgi_param REMOTE_PORT $remote_port;
            fastcgi_param SERVER_ADDR $server_addr;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param SERVER_NAME $server_name;
        }
    }
