---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beerfestdb-code-pv-volume
  labels:
    type: local
    name: beerfestdb-codevol
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/home/tfrayner/src/beerfestdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beerfestdb-code-pv-claim
  namespace: beerfestdb
spec:
  selector:
    matchLabels:
      name: beerfestdb-codevol
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beerfestdb
  name: beerfestdb-app
  labels:
    app: beerfestdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerfestdb-app
  template:
    metadata:
      labels:
        app: beerfestdb-app
    spec:
      containers:
      - name: beerfestdb
        image: tfrayner/beerfestdb:1.1
        imagePullPolicy: IfNotPresent
        command: ["beerfestdb_web_fastcgi.pl", "-l", ":3000", "-n", "1"]
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: '1'
            memory: 4G
          requests:
            cpu: 10m
            memory: 200Mi
        securityContext:
          runAsUser: 65534  # nobody user
        envFrom:
        - configMapRef:
            name: beerfestdb-app-config
        volumeMounts:
        - mountPath: /usr/src/BeerFestDB
          name: beerfestdb-codevol
        workingDir: /usr/src/BeerFestDB
      volumes:
      - name: beerfestdb-codevol
        persistentVolumeClaim:
          claimName: beerfestdb-code-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  namespace: beerfestdb
  name: beerfestdb-app-service
spec:
  selector:
    app: beerfestdb-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx
  labels:
    app: beerfestdb-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerfestdb-nginx
  template:
    metadata:
      labels:
        app: beerfestdb-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.7-perl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: '1'
            memory: 4G
          requests:
            cpu: 10m
            memory: 200Mi
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: beerfestdb-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx-service
spec:
  selector:
    app: beerfestdb-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  namespace: beerfestdb
  name: beerfestdb-ingress
spec:
  entryPoints:
    - bfdbsecure
  routes:
  - match: PathPrefix(`/`)
    kind: Rule
    services:
    - name: beerfestdb-nginx-service
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: beerfestdb
  name: beerfestdb-nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            fastcgi_pass beerfestdb-app-service:3000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param CONTENT_TYPE $content_type;
            fastcgi_param CONTENT_LENGTH $content_length;

            fastcgi_param SCRIPT_NAME  '';  
            fastcgi_param PATH_INFO $fastcgi_script_name; 
            fastcgi_param REQUEST_URI $request_uri;
            fastcgi_param DOCUMENT_URI $document_uri;
            fastcgi_param DOCUMENT_ROOT $document_root;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
  
            fastcgi_param GATEWAY_INTERFACE  CGI/1.1;
            fastcgi_param SERVER_SOFTWARE  nginx/$nginx_version;
  
            fastcgi_param REMOTE_ADDR $remote_addr;
            fastcgi_param REMOTE_PORT $remote_port;
            fastcgi_param SERVER_ADDR $server_addr;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param SERVER_NAME $server_name;
        }
    }
