apiVersion: v1
kind: Namespace
metadata:
  name: beerfestdb
  labels:
    name: beerfestdb
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: beerfestdb
spec:
  hard:
    cpu: '2'
    memory: '8Gi'
    pods: '6'
    resourcequotas: '1'
    services: '6'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beerfestdb-mysql-pv-volume
  labels:
    type: local
    name: beerfestdb-dbvol
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  ## Change this path to point to the location where you want MySQL to store its data on the
  ## host machine.
  hostPath:
    path: "/srv/beerfestdb/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: beerfestdb
spec:
  selector:
    matchLabels:
      name: beerfestdb-dbvol
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: beerfestdb-mysqlinit-pv-volume
  labels:
    type: local
    name: beerfestdb-initvol
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  ## Change this path to point to the location of the BeerFestDB SQL init
  ## scripts (the `db` directory, or a directory containing a mysql dump from a previous backup).
  hostPath:
    path: "/home/tfrayner/src/beerfestdb/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlinit-pv-claim
  namespace: beerfestdb
spec:
  selector:
    matchLabels:
      name: beerfestdb-initvol
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
---
## The following PV+PVC only needed for local development with a bind mount of the source code. 
## If omitted, the app will run with the default code baked into the image.
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: beerfestdb-code-pv-volume
#   labels:
#     type: local
#     name: beerfestdb-codevol
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadOnlyMany
#   hostPath:
#     path: "/home/tfrayner/src/beerfestdb"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: beerfestdb-code-pv-claim
#   namespace: beerfestdb
# spec:
#   selector:
#     matchLabels:
#       name: beerfestdb-codevol
#   storageClassName: manual
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 1Gi
# ---
