##
## This file is part of BeerFestDB, a beer festival product management
## system.
##
## Copyright (C) 2011 Tim F. Rayner
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## $Id$

###############################################################################
#' Turn-key festival sales analysis
#' @description Takes the dip data frame generated by
#'   \code{\link{getFestivalData}} and writes out a set of PDFs illustrating
#'   some of the more interesting features of the sales data.  Also writes a
#'   CSV file of per-product sales rankings to the current working directory.
#' @details Condemned casks are excluded before analysis.  Beer ABV is cut
#'   into six classes.  The following output files are produced in the current
#'   working directory:
#'   \describe{
#'     \item{total_beer_sales.pdf}{Overall gallons sold per session.}
#'     \item{sales_by_region.pdf, sales_by_stillage.pdf, sales_by_abv_class.pdf}{Fraction-remaining profiles grouped by category.}
#'     \item{beers_per_region.pdf, beers_per_style.pdf}{Pie charts of product counts per category.}
#'     \item{clusters_by_style.pdf}{Heatmap of cumulative sales by style over time.}
#'     \item{sale_profile_by_*.pdf}{Bar charts comparing observed and predicted sales shares by category.}
#'     \item{product_sales_ranking.csv}{Per-product sale-rate ranking from \code{\link{rankProducts}}.}
#'   }
#' @param festival The data frame generated by \code{\link{getFestivalData}}.
#' @return Invisibly returns the product-ranking data frame (see
#'   \code{\link{rankProducts}}).
#' @seealso \code{\link{getFestivalData}}, \code{\link{rankProducts}},
#'   \code{\link{plotSalesRate}}, \code{\link{plotModelCoeffs}}
#' @importFrom RColorBrewer brewer.pal
#' @importFrom gplots heatmap.2
#' @importFrom stats aggregate
#' @importFrom utils write.csv
#' @export
###############################################################################
analyseData <- function(festival) {
  festival <- festival$subset(is_condemned = 0)

  plotToFile("total_beer_sales.pdf", plotTotalBeerSales, festival)

  plotToFile("sales_by_region.pdf", plotSalesRate, festival, "region")
  plotToFile("sales_by_stillage.pdf", plotSalesRate, festival, "stillage")
  plotToFile("sales_by_abv_class.pdf", plotSalesRate, festival, "abv_class")

  cols <- brewer.pal(9, "Set1")
  byprod <- with(festival$data, aggregate(data.frame(region, style),
                      list(company_name, product_name), unique))
  plotToFile("beers_per_region.pdf", drawPie,
    byprod, "region",
    cols = cols, cex = 1.25,
    .echo = FALSE
  )
  plotToFile("beers_per_style.pdf", drawPie,
    byprod, "style",
    cols = cols, cex = 1.25,
    .echo = FALSE
  )

  d <- festival$grouped_per_diem_sales('style') %>% column_to_rownames('style')

  plotToFile("clusters_by_style.pdf", heatmap.2, as.matrix(t(scale(t(d)))),
          dendrogram='none', key=FALSE, margins=c(5,12), trace='none',
          Colv=FALSE, lhei=c(2, 10), lwid=c(2, 5), cexRow=1.5, cexCol=1.5,
          .echo = FALSE
  )

  ## Drop the last part of the festival (1/4 rounded up) since it'll
  ## usually be non-linear by then.
  drop <- rev(rev(colnames(d))[ seq_len(ceiling(ncol(d)/4)) ])

  plotToFile("sale_profile_by_style.pdf", plotModelCoeffs, festival, "style",
             drop = drop)
  plotToFile("sale_profile_by_abv_class.pdf", plotModelCoeffs, festival, "abv_class",
             drop = drop)
  plotToFile("sale_profile_by_region.pdf", plotModelCoeffs, festival, "region",
             drop = drop)
  plotToFile("sale_profile_by_stillage.pdf", plotModelCoeffs, festival, "stillage",
             drop = drop)

  ## Probably don't want to publish this until we're happier with
  ## the algorithm.
  prodrank <- rankProducts(festival, drop = drop)
  write.csv(prodrank, file = "product_sales_ranking.csv", row.names = FALSE)

  invisible(prodrank)
}
