##
## This file is part of BeerFestDB, a beer festival product management
## system.
##
## Copyright (C) 2011-2026 Tim F. Rayner
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
## $Id$

###############################################################################
#' Rank products by their observed sale rate (experimental)
#' @description Estimates the sale rate for each active cask using a linear
#'   model, averages the per-cask rates by product, and returns products
#'   sorted from slowest to fastest seller.  This is quite experimental due
#'   to the complexities of determining a sale rate from sparse data affected
#'   by multiple confounding factors.
#' @details Casks that show no change over the query period are excluded
#'   before fitting.  Each cask's rate is estimated independently via
#'   \code{\link{caskSaleRate}} and then averaged across all casks of the
#'   same product.  The \code{drop} argument is used to exclude the final
#'   sessions of the festival, where sales typically become non-linear.
#' @param festival A Festival object generated by \code{\link{getFestivalData}}.
#' @param drop A character vector of dip-time column names to exclude from
#'   the analysis (typically the last sessions of the festival).
#' @return A data frame with one row per product, sorted ascending by
#'   \code{gallons_per_session}.  Columns: \code{company_name},
#'   \code{product_name}, \code{style}, \code{abv},
#'   \code{gallons_per_session}.
#' @seealso \code{\link{caskSaleRate}}, \code{\link{analyseData}}
#' @importFrom dplyr %>% group_by summarise arrange
#' @importFrom stats lm aggregate
#' @export
###############################################################################
rankProducts <- function(festival, drop) {
  ## Our initial attempt at this aggregated the data by product and then fitted 
  ## a linear model to the aggregated data. This is not a good idea since it assumes
  ## that all casks of a product are started immediately one after another without delay.
  ## In reality, we occasionally hold casks back to keep some available for later sessions.

  ## We instead use a better approach: once a cask is started, it's not usually held
  ## back any further. We calculate sales rates per cask and take the mean.
  ## This also works most believably if we drop the last part
  ## of the festival where sales run into non-linear territory (effectively, right-censored data);
  ## note that some beers lose out in this case. Alternative models are available.
  x <- festival$grouped_dips(c('festival_ref', 'company_name','product_name','style','abv'))
  x <- x[, !colnames(x) %in% drop]

  ## Have to throw out all those beers which never changed in the query period.
  x <- x[apply(x[, -c(1:5)], 1, function(x) {
    sum(x != x[1])
  }) != 0, ]

  x <- x %>%
    cbind(as.data.frame(t(apply(x[, -c(1:5)], 1, caskSaleRate)))) %>%
    group_by(company_name, product_name, style, abv) %>%
    summarise(gallons_per_session = mean(Estimate)) %>%
    arrange(desc(gallons_per_session))

  return(x)
}
