name: Docker Image CI

on:
  push:
    branches: [ "cbf-production" ]
  pull_request:
    branches: [ "cbf-production" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tfrayner/beerfestdb:$(date +%s)
