name: Docker Image CI/CD

on:
  push:
    branches: [ "cbf-production" ]

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.19.2
      with:
        push: true
        tags: tfrayner/beerfestdb:latest

  r-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: R/BeerFestDB
        extra-packages: any::testthat, any::devtools

    - name: Build R package
      working-directory: R/BeerFestDB
      run: Rscript -e "devtools::check(vignettes = FALSE, error_on = 'error'); devtools::build(path = '.', vignettes = FALSE, manual = TRUE)"

    - uses: actions/upload-artifact@v4
      with:
        name: beerfestdb-r-package
        path: R/BeerFestDB/*.tar.gz
